### ISSUE TITLE
Inconsistent window control styling

### ISSUE THREAD

**Issue by arcticicestudio** [microsoft/theme-converter-for-vs#106]
The control buttons (minimize, maximize and close) of the main IDE window using a different style than the ones of the launcher window.
In my opinion the background color should be more subtle to not disturb the focus of the user as these components also do not play an important role during actual IDE usage.

<p align="center"><strong>The control buttons of the launcher window with "Nord" as active VS theme.</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/132989207-d677bdf5-52b8-4fc7-b71d-922f65003d44.png"></p>

<p align="center"><strong>In comparison the control buttons of the main IDE window with "Nord" as active VS theme.</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/132989169-ba002bed-9f77-4951-bf04-9d97e185b439.png"></p>

<p align="center"><strong>The problem reported in #105 can also be seen on the window control buttons.</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/132989412-0069dd06-4f9b-4a15-bcc5-761c0007e932.png"></p>

I've checked the Nord VS Code theme and found the following keys that are responsible for semantic occurrence highlighting:

- `button.background` - the key for the background color of button components.
- `button.hoverBackground` - the key for the background color of button components when being hovered with the mouse.

#### Reproduction Steps

1. Set Nord as active theme.
2. Open VS and validate that the background color of the window control buttons are a bright color ([`nord8`][2]).
3. Open any project and validate that the window control buttons are now using subtle background color (same as window top bar).

#### Expected Behavior

I expected that the control buttons of the launcher window use the same style like the main IDE window to not disturb the focus of the user as these components also do not play an important role during actual IDe usage.

#### Environment

**Converter version**: commit 34bbde361cb3511f7b6ae99dd2689c1825cca60e
**VS version**: `17.0.0 Preview 3`
**Theme(s) used**: [Nord][1]

#### (Possible) Release Impact

This issue is kind of a low annoyance that can be improved in a future version and it not a blocker for a theme release.

[1]: https://marketplace.visualstudio.com/items?itemName=arcticicestudio.nord-visual-studio-code
[2]: https://www.nordtheme.com/docs/colors-and-palettes#nord8

**Comment by ketttY** [comment]
Thank you for sharing the feedback, @arcticicestudio! The issue should now be fixed, feel free to reopen it if it still reproduces for you!
