### ISSUE TITLE
Not all XAML Designers tokens are converted and they fail editor

### ISSUE THREAD

**Issue by dempfi** [microsoft/theme-converter-for-vs#108]
**Describe the bug**
I've got a [report today from a user](https://marketplace.visualstudio.com/items?itemName=dempfi.ayu-vs&ssr=false#review-details) that XAML Designer is failing for them when ayu is activated. I've checked and apparently if some tokens that are used in the XAML designer window are not mapped they fail the window.

**Screenshots**

<img width="1459" alt="Screen Shot 2021-09-15 at 11 28 19 AM" src="https://user-images.githubusercontent.com/4568573/133398545-c675e26d-7c7d-4d02-a981-e8f01aef3de0.png">

**To Reproduce**
- Install and activate ayu https://marketplace.visualstudio.com/items?itemName=dempfi.ayu-vs
- Create a WPF project
- Open XAML designer

**Expected behavior**
Fallback to light theme or auto conversion

**Environment (please complete the following information):**
 - Converter version: [e.g. v0.0.2]
 - VS version: [e.g. 16.10.2, 17.0.0 Preview 3]
 - Theme used: [e.g. [Panda](https://marketplace.visualstudio.com/items?itemName=tinkertrain.theme-panda)]

**Impact**
Please describe how this bug impacts your theme. Is this bug blocking you from releasing the theme, or is this a mild annoyance?

**Additional context**

**Comment by ketttY** [comment]
Thank you again for sharing the feedback, @dempfi! The issue should now be fixed, feel free to reopen if it still reproduces for you!
