### ISSUE TITLE
Light+ Theme menu items have wrong background color when focused out of VS

### ISSUE THREAD

**Issue by hutchcodes** [microsoft/theme-converter-for-vs#114]
**Describe the bug**
When using the Light+ theme the menu items (File, Edit View etc) have the wrong background color if Visual Studio isn't the app with focus.

**Screenshots**
![Toolbar](https://user-images.githubusercontent.com/4989220/134206287-66e57f55-0822-4f5a-80d0-792376b39de3.png)

**To Reproduce**
1. Change to Light+ theme
2. Click on the desktop or another app to change focus away from Visual Studio
3. See the background of the menu items

**Expected behavior**
Background of menu items should match that of the toolbar.

**Environment (please complete the following information):**
 - Converter version: Visual Studio Theme Pack V1.0
 - VS version: 17.0.0 Preview 4.0
 - Theme used: Light+

**Impact**
Very minor, it's not even the focused app at the time

**Additional context**

**Comment by hutchcodes** [comment]
I just realized this is the repo for the converter, not the theme packs. So maybe there is somewhere else I should be filing these bugs (I have another for the Light+ theme). Feel free to redirect me and close this.

**Comment by huguesv** [comment]
@hutchcodes this is the right place to file these issues (the theme pack was created using the converter). Thanks for the feedback!

**Comment by ketttY** [comment]
Thank you again for sharing the feedback, @hutchcodes! The issue should now be fixed, feel free to reopen if it still reproduces for you!
