### ISSUE TITLE
Light+ has wrong whitespace dot color

### ISSUE THREAD

**Issue by hutchcodes** [microsoft/theme-converter-for-vs#116]
**Describe the bug**
The whitespace dots in Light+ is a fairly saturated blue in Visual Studio but is a light gray in VS Code

**Screenshots**
Whitespace dots in Visual Studio
![image](https://user-images.githubusercontent.com/4989220/134225137-a7ed0381-c086-40a3-8cf0-bf74901557ec.png)

Whitespace dots in VS Code
![image](https://user-images.githubusercontent.com/4989220/134224965-a5ceeae1-6d26-4193-939b-c7f2241195e4.png)

**To Reproduce**
1. Select Light+ theme
2. Go to Tools->Options->Text Editor and check "View whitespace"
3. Open a code file
4. See blue whitespace dots

**Expected behavior**
Whitespace dots should be light gray

**Environment (please complete the following information):**
 - Converter version: [Theme Pack v1.0]
 - VS version: [17.0.0 Preview 4]
 - Theme used: Light+

**Impact**
Minor annoyance, but enough that I turn of "View whitespace" despite my preference to have it on.

**Comment by gracegtaylor** [comment]
Thanks for sharing this issue, @hutchcodes, we can look into this issue and prioritize it. The dots do look quite distracting with that kind of coloring.

**Comment by ketttY** [comment]
Thank you again for sharing the feedback, @hutchcodes! The issue should now be fixed, feel free to reopen if it still reproduces for you!
