### ISSUE TITLE
AppCap Overview pages have the wrong colors

### ISSUE THREAD

**Issue by 9at8** [microsoft/theme-converter-for-vs#134]
The `ACDCOverview&Body&Background` token is incorrectly mapped.
https://github.com/microsoft/theme-converter-for-vs/blob/bbb9f073b1535e20e82e3322900c0af6e4029ad4/ThemeConverter/ThemeConverter/TokenMappings.json#L2341

**Screenshots**

Light+ theme from Visual Studio Theme Pack:

![image](https://user-images.githubusercontent.com/8235156/146274566-e1f3a636-f06c-4d48-a7c5-a6810d733a11.png)

Solarized Light:

![image](https://user-images.githubusercontent.com/8235156/146274601-26f3e0b8-827e-4fe9-94f7-9d48db1373f1.png)

Solarized Dark:

![image](https://user-images.githubusercontent.com/8235156/146274625-3b868371-069f-4047-9c15-0552a91d33e3.png)

**To Reproduce**

1. Create a new ASP.NET Core Web App
2. Look at the overview page
3. If you've already opened up an ASP.NET Core Web App solution, then `Project > Overview`

**Expected behavior**

Builtin light theme:

![image](https://user-images.githubusercontent.com/8235156/146274483-cd2f7012-39f5-429f-9524-a8bd19a8392d.png)

**Environment (please complete the following information):**
 - Converter version: [e.g. v0.0.2]
 - VS version: Version 17.1.0 Preview 3.0 [32013.77.main]
 - Theme used: [e.g. [Light+](https://marketplace.visualstudio.com/items?itemName=idex.vsthemepack)]

**Impact**
I'm not converting a new theme, but I guess it could be a mild annoyance.

**Comment by huguesv** [comment]
Thanks for the report!
