### ISSUE TITLE
Solarized light: Unittest popup links are not readable

### ISSUE THREAD

**Issue by erikmourits** [microsoft/theme-converter-for-vs#138]
**Describe the bug**
Solarized light: Unittest popup links are not readable

**Screenshots**
![image](https://user-images.githubusercontent.com/1277119/148509322-a586262c-610a-49fd-a3ad-ec3cab39df8a.png)

**To Reproduce**
1. Activate the Solarized Light theme
2. Go to a unittest
3. Above the unittest method name, click on the icon (blue if not yet run, green if passing)
4. A popup appears and show a few links: run, debug, etc.
5. These links are a light color (not quite white) and the background of the popup is white.

**Expected behavior**
The links should be a dark color, so that the contrast between the link and the background is high.

**Environment (please complete the following information):**
 - Converter version: (unknown, using the theme pack: https://marketplace.visualstudio.com/items?itemName=idex.vsthemepack)
 - VS version: 17.0.1
 - Theme used: Solarized Light 

**Impact**
It's pretty annoying. But workable.

**Comment by ketttY** [comment]
Hi @erikmourits, thank you for adding the details! We have a fix ready in #139 with some screenshots. Feel free to take a look and see if that matches your expectation! After the PR is merged, the fix will be released with the next version of theme pack!

**Comment by erikmourits** [comment]
@ketttY It works! Thanks :)
