### ISSUE TITLE
Incorrect main menu colours for inactive elements

### ISSUE THREAD

**Issue by fwosar** [microsoft/theme-converter-for-vs#142]
**Describe the bug**
When attempting to convert the Dracula Pro Van Helsing theme to VS2022 using the converter I noticed that all disabled main and context menu entries are themed incorrectly.

**Screenshots**
Here is what these entries are supposed to look like based on Visual Studio Code:

![image](https://user-images.githubusercontent.com/489494/163681443-ed8fdee0-2210-4072-b6b6-50025914c09c.png)

![image](https://user-images.githubusercontent.com/489494/163681478-acb4239e-3ead-4ae2-ba41-a1de00e6879f.png)

Here is what they look like in Visual Studio 2022:

![image](https://user-images.githubusercontent.com/489494/163681545-6b266c7b-4030-40d2-b598-891820d45ade.png)

![image](https://user-images.githubusercontent.com/489494/163681515-b20da2d6-cf17-4733-9ecc-1969bcb78ef3.png)

**To Reproduce**
Simply attempt to convert the theme. 

**Expected behavior**
Context and main menu items should have the correct disabled theming. 

**Environment (please complete the following information):**
Latest ThemeConverter compiled from the master branch. 
Visual Studio 2022

Theme is a commercial theme, but it can be reproduced with the normal [freely available Dracula theme as well](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula). In fact, the ["official" conversion of Dracula](https://marketplace.visualstudio.com/items?itemName=dracula-theme.dracula) that was advertised by a recent Microsoft blog post has exactly the same issue.

**Impact**
Makes using the converted theme completely impossible as there is no way to differentiate between enabled and disabled context and main menu items unless there is a glyph or icon involved. I actually didn't notice it at first and only noticed it after I was wondering why a certain menu option wasn't working for close to 30 minutes.

**Additional context**
The same appears to be true for the official Dracula conversions available in the store as well.

**Comment by fwosar** [comment]
I checked out some more themes and this appears to be a universal issue that isn't limited to one theme. In fact, in the [official video announcement](https://youtu.be/2Gwqr5uuBt4?t=259), you can watch it live in action. Just pay attention to the context menu and the Copy, Cut, and Paste entries in particular.

I am genuinely surprised that seemingly nobody noticed this before.

**Comment by fwosar** [comment]
After doing some digging it turns out that Visual Studio Code uses opacity (0.4) to "grey out" inactive entries within the context and main menus. Therefore, the fix would probably involve calculating a compound colour based on the background as well as the foreground colour for Environment/CommandBarTextInactive.

**Comment by ketttY** [comment]
Hi @fwosar, thank you so much for your feedback! We will look into this issue and let you know once we have a fix for it!
