### ISSUE TITLE
Error List pane resize separator

### ISSUE THREAD

**Issue by Binaryify** [microsoft/theme-converter-for-vs#147]
**Describe the bug**
It is difficult to see where to place the cursor for resizing the Error List pane when a file is open in the most recent update.

**Screenshots**
![](https://user-images.githubusercontent.com/812974/172426519-f573f594-23f4-40f2-b872-f49f84a38c57.gif)

Repeat https://github.com/Binaryify/OneDark-Pro/issues/740

It should have a split line 
In vscode, it look like this
<img width="1865" alt="image" src="https://user-images.githubusercontent.com/12221718/172576403-bf58d976-230a-4bca-a291-6c006568f27a.png">

**Comment by ryanbuening** [comment]
Adding some clarification...this would occur on any pane docked there, not just the error list.

**Comment by ketttY** [comment]
Hi @Binaryify, sorry for the delayed response, got some high-priority tasks that need to be addressed. I have tried reproducing this issue with One Dark Pro, One Dark Pro Darker, One Dark Pro Flat and One Dark Pro Mix, but none of them produced result like the one in the gif. I am wondering can you let me know which version of One Dark Pro you converted for the official extension? Thank you!

**Comment by Binaryify** [comment]
@ryanbuening

**Comment by Binaryify** [comment]
@ketttY I used this json file which generate from the vscode's generate from current theme command
https://gist.github.com/Binaryify/81fd565c1ac851b9cf55e852c77caa01

**Comment by Binaryify** [comment]
also the vs's version is 17.2.3

**Comment by ryanbuening** [comment]
I'm on 17.2.5

OneDark-Pro (Binaryify) theme:

![image](https://user-images.githubusercontent.com/812974/175189838-7a7904bf-502b-4025-98bd-3704141e5de2.png)


Default Dark theme:

![image](https://user-images.githubusercontent.com/812974/175189777-c667996f-5b10-4957-acbc-3bee60073b59.png)

**Comment by ketttY** [comment]
@Binaryify and @ryanbuening, thank you both for the clarification! I have created #148 to address this issue. Feel free to take a look and see if that meets your expectations! Thank you!

**Comment by Binaryify** [comment]
thank for the fast response, I just re-generate a new vsix and it look great

**Comment by ryanbuening** [comment]
@ketttY, could a similar thing be done (border) for the tab pane when tabs are placed on the left?...

![image](https://user-images.githubusercontent.com/812974/175557189-ac40c6c8-6164-4b31-9a3a-c73aa65008bd.png)

**Comment by ketttY** [comment]
@ryanbuening, after checking, it looks like VS does not have a border token for that area, so for now the theme converter can't add a border there. Apologize for the inconvenience.
