### ISSUE TITLE
Does still preview version of Visual Studio 2022 may affect the result?

### ISSUE THREAD

**Issue by inlineHamed** [microsoft/theme-converter-for-vs#152]
In prerequisites section of README.md file is stated that VS 2022 Preview 3 or later would bring the best result. 

As visual Studio 2022 (17.0) was released about a year ago and still there are preview versions for next minor release (currently 17.3 preview), I think this statement should be updated to simply saying Visual Studio 2022 or specifying the exact minor version it need for best result.

**Comment by huguesv** [comment]
You're right, the README hasn't been updated since VS 2022 was released. It should work fine with 17.0 or later. No need for preview builds. We'll update the README.
