### ISSUE TITLE
How do i delete a theme that got added to my visual studio?

### ISSUE THREAD

**Issue by khaledmoayad** [microsoft/theme-converter-for-vs#160]

**Comment by gregop** [comment]
Hello @khaledmoayad, you can do so by following the steps below (these instructions can also be found [here](https://github.com/microsoft/theme-converter-for-vs#removing-a-converted-theme-from-vs), in the Repo's  readme.md): 

  1. You will need to remove the .pkgdef file that you have created using this project.
   Go to the directory that your target VS is installed, and navigate to `<vs_install_dir>\Common7\IDE\CommonExtensions\Platform`. e.g: `C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Platform`
   
1. Delete the .pkgdef of the theme that the you want to remove (The name of the pkgdef will match the name of the theme). 
 If you have created this theme, then the name of the theme would be `<name-given>.pkgdef`
 
 1. Open Developer Command Prompt of the targe VS, and 
    Select **Terminal** under **View** of the menu bar (or press Ctrl+') 
    run >  `devenv /updateConfiguration`

    
1. Close and Launch again Visual Studio again. The theme should now be removed
   Check this via Tools &rarr; Themes

**Comment by gregop** [comment]
Greetings!! can I be assigned to this issue?

**Comment by khaledmoayad** [comment]
Absolutely, thanks for the help!

**Comment by gracegtaylor** [comment]
Thanks, @gregop!
